### ISSUE TITLE
Exact search feature

### ISSUE THREAD

**Issue by parsa-segment** [getmetamapper/metamapper#65]
## Feature

Return **exact** matches when the search term is enclosed in double-quotes.

## Motivation

This feature would enable the user to narrow down the search results.

**Comment by scruwys** [comment]
Great idea. We're using Elastic for search, so this could be as simple as allowing users to write search queries using the [Lucene](https://github.com/mcandre/cheatsheets/blob/master/lucene.md) query syntax.

There are a few improvements to the Elastic tokenizer that need to be made as well. We can likely push this with `v0.3.1` sometime late next week.

**Comment by scruwys** [comment]
See #71. Migrated ElasticSearch from `multi_match` to `simple_query_string` which supports exact searches when using double-quotes. For example, a search like `start a search "party"` will return results directly related to the term `party` and somewhat related to the other terms in that sentence.

Closing this as solved. Thanks!
